### ISSUE TITLE
Q-form-builder with laravel mix

### ISSUE THREAD

**Issue by exiliensoft** [baggachipz/q-form-builder#9]
Hey,
I have used this code as Vue and it is a good platform. I really like it.
and I want to use this builder into Laravel as a dynamic builder for form creation. you have any suggestion regarding this as npm package is not working fine.
so I hope you can suggest something to me for this.

**Comment by baggachipz** [comment]
Could you post the error you get as an NPM package?

**Comment by exiliensoft** [comment]
![npm package error](https://user-images.githubusercontent.com/18166074/87749495-78381b00-c816-11ea-8e6e-ff4d7b03072d.png)
this is the error I am facing as using the npm package in the Laravel mix.
actually my requirement is I need to provide drag and drop functionality to create a form and that form can be used in Laravel + Vue as Laravel mix.
Or please guide me the steps to integrate it within Vue + Laravel.
Thanks in advance

**Comment by exiliensoft** [comment]
I have tried to do it and somewhat successful but I am getting this error.
if you have any solution regarding .styl compilation in Laravel mix version 5. Please let me know.
this is the error.

ERROR in ./resources/js/styles/quasar.styl
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ModuleBuildError: Module build failed (from ./node_modules/stylus-loader/index.js):
Error: E:\vue laravel projects\new 16-july\blog\resources\js\styles\quasar.variables.styl:13:9
    9| $negative  = #C10015
   10| $info      = #31CCEC
   11| $warning   = #F2C037
   12|
   13| @import '~quasar-variables-styl'
---------------^
   14|

failed to locate @import file ~quasar-variables-styl.styl

    at CachedPathEvaluator.visitImport (E:\vue laravel projects\new 16-july\blog\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitBlock (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at CachedPathEvaluator.Visitor.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.importFile (E:\vue laravel projects\new 16-july\blog\node_modules\stylus-loader\lib\evaluator.js:84:18)
    at CachedPathEvaluator.visitImport (E:\vue laravel projects\new 16-july\blog\node_modules\stylus-loader\lib\evaluator.js:162:27)
    at CachedPathEvaluator.Visitor.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\renderer.js:86:26)
    at E:\vue laravel projects\new 16-july\blog\node_modules\stylus-loader\index.js:167:12
    at tryCatchReject (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\Scheduler.js:27:9)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
    at E:\vue laravel projects\new 16-july\blog\node_modules\webpack\lib\NormalModule.js:316:20
    at E:\vue laravel projects\new 16-july\blog\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\vue laravel projects\new 16-july\blog\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\vue laravel projects\new 16-july\blog\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at E:\vue laravel projects\new 16-july\blog\node_modules\stylus-loader\index.js:169:11
    at Renderer.render (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\renderer.js:107:12)
    at E:\vue laravel projects\new 16-july\blog\node_modules\stylus-loader\index.js:167:12
    at tryCatchReject (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\Scheduler.js:27:9)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 @ multi ./resources/js/app.js ./resources/sass/app.scss ./resources/js/styles/quasar.styl /js/app[2]

ERROR in ./resources/js/styles/quasar.styl
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ModuleBuildError: Module build failed (from ./node_modules/stylus-loader/index.js):
Error: E:\vue laravel projects\new 16-july\blog\resources\js\styles\quasar.variables.styl:13:9
    9| $negative  = #C10015
   10| $info      = #31CCEC
   11| $warning   = #F2C037
   12|
   13| @import '~quasar-variables-styl'
---------------^
   14|

failed to locate @import file ~quasar-variables-styl.styl

    at CachedPathEvaluator.visitImport (E:\vue laravel projects\new 16-july\blog\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitBlock (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at CachedPathEvaluator.Visitor.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.importFile (E:\vue laravel projects\new 16-july\blog\node_modules\stylus-loader\lib\evaluator.js:84:18)
    at CachedPathEvaluator.visitImport (E:\vue laravel projects\new 16-july\blog\node_modules\stylus-loader\lib\evaluator.js:162:27)
    at CachedPathEvaluator.Visitor.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\renderer.js:86:26)
    at E:\vue laravel projects\new 16-july\blog\node_modules\stylus-loader\index.js:167:12
    at tryCatchReject (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\Scheduler.js:27:9)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
    at E:\vue laravel projects\new 16-july\blog\node_modules\webpack\lib\NormalModule.js:316:20
    at E:\vue laravel projects\new 16-july\blog\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\vue laravel projects\new 16-july\blog\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\vue laravel projects\new 16-july\blog\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at E:\vue laravel projects\new 16-july\blog\node_modules\stylus-loader\index.js:169:11
    at Renderer.render (E:\vue laravel projects\new 16-july\blog\node_modules\stylus\lib\renderer.js:107:12)
    at E:\vue laravel projects\new 16-july\blog\node_modules\stylus-loader\index.js:167:12
    at tryCatchReject (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (E:\vue laravel projects\new 16-july\blog\node_modules\when\lib\Scheduler.js:27:9)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 @ ./resources/js/styles/quasar.styl

**Comment by exiliensoft** [comment]
Thanks.
I have sorted out this issue and it is working fine for me now.
